/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 12 16:07:57 GMT 2019
 */

package org.springframework.samples.petclinic.evo_sixty_seconds;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.samples.petclinic.PetClinicApplication;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.fail;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class PetClinicApplication_ESTest extends PetClinicApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PetClinicApplication petClinicApplication0 = new PetClinicApplication();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[6];
      // Undeclared exception!
      try {
        PetClinicApplication.main(stringArray0);
        fail("Expecting exception: NoClassDefFoundError");

      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/boot/SpringApplication
         //
         verifyException("org.springframework.samples.petclinic.PetClinicApplication", e);
      }
  }
}
