/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 12 16:09:18 GMT 2019
 */

package org.springframework.samples.petclinic.evo_sixty_seconds;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.samples.petclinic.system.WelcomeController;

import static org.junit.Assert.assertEquals;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class WelcomeController_ESTest extends WelcomeController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WelcomeController welcomeController0 = new WelcomeController();
      String string0 = welcomeController0.welcome();
      assertEquals("welcome", string0);
  }
}
