/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 13 00:17:53 GMT 2019
 */

package dummiesmind.breadcrumb.springmvc.evo_sixty_seconds.dummiesmind.breadcrumb.springmvc.breadcrumb;

import dummiesmind.breadcrumb.springmvc.breadcrumb.BreadCrumbLink_ESTest_scaffolding;
import org.junit.Test;
import static org.junit.Assert.*;
import dummiesmind.breadcrumb.springmvc.breadcrumb.BreadCrumbLink;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BreadCrumbLink_ESTest extends BreadCrumbLink_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("Cmgi9>@s-{N", "Cmgi9>@s-{N", false, "Cmgi9>@s-{N");
      assertFalse(breadCrumbLink0.isCurrentPage());
      
      breadCrumbLink0.setCurrentPage(true);
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      BreadCrumbLink breadCrumbLink1 = new BreadCrumbLink("0S6)N8H+ba;VjoPaO4", "R\"B]_IPC.|[:D]", false, "");
      breadCrumbLink1.addNext(breadCrumbLink0);
      assertEquals("0S6)N8H+ba;VjoPaO4", breadCrumbLink1.getFamily());
      assertEquals("", breadCrumbLink1.getParentKey());
      assertEquals("R\"B]_IPC.|[:D]", breadCrumbLink1.getLabel());
      assertFalse(breadCrumbLink1.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      BreadCrumbLink breadCrumbLink1 = new BreadCrumbLink("0S6)N8H+ba;VjoPaO4", "R\"B]_IPC.|[:D]", false, "");
      breadCrumbLink0.setPrevious(breadCrumbLink1);
      assertFalse(breadCrumbLink1.isCurrentPage());
      assertEquals("R\"B]_IPC.|[:D]", breadCrumbLink1.getLabel());
      assertEquals("", breadCrumbLink1.getParentKey());
      assertEquals("0S6)N8H+ba;VjoPaO4", breadCrumbLink1.getFamily());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      boolean boolean0 = breadCrumbLink0.isCurrentPage();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      breadCrumbLink0.setUrl("Xp:Pwle$(Ls6<C0_e");
      breadCrumbLink0.getUrl();
      assertFalse(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      breadCrumbLink0.setUrl("");
      breadCrumbLink0.getUrl();
      assertFalse(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      breadCrumbLink0.setPrevious(breadCrumbLink0);
      BreadCrumbLink breadCrumbLink1 = breadCrumbLink0.getPrevious();
      assertFalse(breadCrumbLink1.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("0S6)N8H+baJVjoPaO0", "J@w&g*.GoG<+Wx", false, "1>{Z~sj@ V,Om?=");
      String string0 = breadCrumbLink0.getParentKey();
      assertEquals("J@w&g*.GoG<+Wx", breadCrumbLink0.getLabel());
      assertEquals("1>{Z~sj@ V,Om?=", string0);
      assertFalse(breadCrumbLink0.isCurrentPage());
      assertEquals("0S6)N8H+baJVjoPaO0", breadCrumbLink0.getFamily());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("0S6)N8H+baJVjoPaO0", "J@w&g*.GoG<+Wx", false, "");
      String string0 = breadCrumbLink0.getParentKey();
      assertEquals("J@w&g*.GoG<+Wx", breadCrumbLink0.getLabel());
      assertFalse(breadCrumbLink0.isCurrentPage());
      assertEquals("", string0);
      assertEquals("0S6)N8H+baJVjoPaO0", breadCrumbLink0.getFamily());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      BreadCrumbLink breadCrumbLink1 = new BreadCrumbLink("0S6)N8H+baJVjoPaO0", "0S6)N8H+baJVjoPaO0", false, "0S6)N8H+baJVjoPaO0");
      breadCrumbLink0.setParent(breadCrumbLink1);
      assertFalse(breadCrumbLink1.isCurrentPage());
      
      breadCrumbLink1.currentPage = false;
      breadCrumbLink1.currentPage = true;
      BreadCrumbLink breadCrumbLink2 = breadCrumbLink0.getParent();
      assertNotSame(breadCrumbLink0, breadCrumbLink2);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      breadCrumbLink0.setParent(breadCrumbLink0);
      BreadCrumbLink breadCrumbLink1 = breadCrumbLink0.getParent();
      assertFalse(breadCrumbLink1.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      breadCrumbLink0.addNext(breadCrumbLink0);
      breadCrumbLink0.getNext();
      assertFalse(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      breadCrumbLink0.setLabel("Qpy{bE6bT-&1");
      breadCrumbLink0.getLabel();
      assertFalse(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      breadCrumbLink0.setLabel("");
      breadCrumbLink0.getLabel();
      assertFalse(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("0S6)N8H+baJVjoPaO0", "J@w&g*.GoG<+Wx", false, "");
      String string0 = breadCrumbLink0.getFamily();
      assertEquals("0S6)N8H+baJVjoPaO0", string0);
      assertEquals("J@w&g*.GoG<+Wx", breadCrumbLink0.getLabel());
      assertEquals("", breadCrumbLink0.getParentKey());
      assertFalse(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      breadCrumbLink0.setFamily("");
      breadCrumbLink0.getFamily();
      assertFalse(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, true, (String) null);
      boolean boolean0 = breadCrumbLink0.isCurrentPage();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, true, (String) null);
      breadCrumbLink0.setPrevious(breadCrumbLink0);
      BreadCrumbLink breadCrumbLink1 = breadCrumbLink0.getPrevious();
      assertTrue(breadCrumbLink1.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      breadCrumbLink0.getFamily();
      assertFalse(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      breadCrumbLink0.getNext();
      assertFalse(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, true, (String) null);
      breadCrumbLink0.getPrevious();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, true, (String) null);
      breadCrumbLink0.getLabel();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, true, (String) null);
      breadCrumbLink0.getParentKey();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, (String) null);
      breadCrumbLink0.getUrl();
      assertFalse(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, true, (String) null);
      breadCrumbLink0.getParent();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, true, (String) null);
      breadCrumbLink0.setParentKey((String) null);
      assertTrue(breadCrumbLink0.isCurrentPage());
  }
}
