/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 12 22:59:24 GMT 2019
 */

package net.guides.springboot.todomanagementspringboot.evo_two_seconds.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import net.guides.springboot.todomanagement.controller.WelcomeController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.ui.ModelMap;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WelcomeController_ESTest extends WelcomeController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WelcomeController welcomeController0 = new WelcomeController();
      ModelMap modelMap0 = new ModelMap();
      // Undeclared exception!
      try { 
        welcomeController0.showWelcomePage(modelMap0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/security/core/context/SecurityContextHolder
         //
         verifyException("net.guides.springboot.todomanagement.controller.WelcomeController", e);
      }
  }
}
