/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 11 01:32:06 GMT 2019
 */

package org.springframework.samples.petclinic.evo_two_seconds;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.samples.petclinic.model.NamedEntity;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class NamedEntity_ESTest extends NamedEntity_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NamedEntity namedEntity0 = new NamedEntity();
      namedEntity0.setName("org.springframework.samples.petclinic.model.BaseEntity");
      String string0 = namedEntity0.toString();
      assertEquals("org.springframework.samples.petclinic.model.BaseEntity", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NamedEntity namedEntity0 = new NamedEntity();
      namedEntity0.setName("");
      String string0 = namedEntity0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NamedEntity namedEntity0 = new NamedEntity();
      namedEntity0.setName("");
      String string0 = namedEntity0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NamedEntity namedEntity0 = new NamedEntity();
      String string0 = namedEntity0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NamedEntity namedEntity0 = new NamedEntity();
      String string0 = namedEntity0.toString();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NamedEntity namedEntity0 = new NamedEntity();
      namedEntity0.setName("0");
      String string0 = namedEntity0.getName();
      assertEquals("0", string0);
  }
}
