/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 11 01:32:41 GMT 2019
 */

package org.springframework.samples.petclinic.evo_two_seconds;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.samples.petclinic.owner.PetType;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class PetType_ESTest extends PetType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PetType petType0 = new PetType();
      assertTrue(petType0.isNew());
  }
}
