/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 12 23:04:09 GMT 2019
 */

package net.guides.springboot.todomanagementspringboot.evo_ten_seconds.model;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Date;
import net.guides.springboot.todomanagement.model.Todo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Todo_ESTest extends Todo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Todo todo0 = new Todo();
      String string0 = todo0.getUserName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MockDate mockDate0 = new MockDate((-961L));
      Todo todo0 = new Todo("]", "", mockDate0, true);
      assertEquals("]", todo0.getUserName());
      
      todo0.setUserName("");
      todo0.getUserName();
      assertEquals("", todo0.getDescription());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Todo todo0 = new Todo();
      Date date0 = todo0.getTargetDate();
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Todo todo0 = new Todo();
      todo0.setId(2064L);
      long long0 = todo0.getId();
      assertEquals(2064L, long0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Todo todo0 = new Todo();
      todo0.setId((-3258L));
      long long0 = todo0.getId();
      assertEquals((-3258L), long0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Todo todo0 = new Todo();
      String string0 = todo0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MockDate mockDate0 = new MockDate((-961L));
      Todo todo0 = new Todo("]", "", mockDate0, true);
      assertEquals("", todo0.getDescription());
      
      todo0.setDescription("]");
      todo0.getDescription();
      assertEquals("]", todo0.getUserName());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MockDate mockDate0 = new MockDate((-961L));
      Todo todo0 = new Todo("]", "", mockDate0, true);
      todo0.setTargetDate(mockDate0);
      assertEquals("", todo0.getDescription());
      assertEquals("]", todo0.getUserName());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MockDate mockDate0 = new MockDate((-961L));
      Todo todo0 = new Todo("]", "", mockDate0, true);
      todo0.getTargetDate();
      assertEquals("", todo0.getDescription());
      assertEquals("]", todo0.getUserName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Todo todo0 = new Todo();
      long long0 = todo0.getId();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MockDate mockDate0 = new MockDate((-961L));
      Todo todo0 = new Todo("]", "", mockDate0, true);
      String string0 = todo0.getDescription();
      assertEquals("]", todo0.getUserName());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MockDate mockDate0 = new MockDate((-961L));
      Todo todo0 = new Todo("]", "", mockDate0, true);
      String string0 = todo0.getUserName();
      assertEquals("", todo0.getDescription());
      assertEquals("]", string0);
  }
}
