/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 13 00:15:36 GMT 2019
 */

package dummiesmind.breadcrumb.springmvc.evo_thirty_seconds.dummiesmind.breadcrumb.springmvc.breadcrumb;

import dummiesmind.breadcrumb.springmvc.breadcrumb.BreadCrumbLink_ESTest_scaffolding;
import org.junit.Test;
import static org.junit.Assert.*;
import dummiesmind.breadcrumb.springmvc.breadcrumb.BreadCrumbLink;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BreadCrumbLink_ESTest extends BreadCrumbLink_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("Ai\"D8N:/F/", "Ai\"D8N:/F/", false, "Ai\"D8N:/F/");
      BreadCrumbLink breadCrumbLink1 = new BreadCrumbLink("Ai\"D8N:/F/", "Ai\"D8N:/F/", true, "");
      breadCrumbLink1.setParent(breadCrumbLink0);
      assertEquals("Ai\"D8N:/F/", breadCrumbLink1.getLabel());
      assertTrue(breadCrumbLink1.isCurrentPage());
      assertEquals("Ai\"D8N:/F/", breadCrumbLink1.getFamily());
      assertEquals("", breadCrumbLink1.getParentKey());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("Ai\"D8N:/F/", "Ai\"D8N:/F/", false, "Ai\"D8N:/F/");
      assertFalse(breadCrumbLink0.isCurrentPage());
      
      breadCrumbLink0.setCurrentPage(true);
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("Ai\"D8N:/F/", "Ai\"D8N:/F/", false, "Ai\"D8N:/F/");
      BreadCrumbLink breadCrumbLink1 = new BreadCrumbLink("Ai\"D8N:/F/", "Ai\"D8N:/F/", true, "");
      breadCrumbLink0.addNext(breadCrumbLink1);
      assertEquals("Ai\"D8N:/F/", breadCrumbLink1.getFamily());
      assertEquals("", breadCrumbLink1.getParentKey());
      assertEquals("Ai\"D8N:/F/", breadCrumbLink1.getLabel());
      assertTrue(breadCrumbLink1.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("", "", true, "");
      BreadCrumbLink breadCrumbLink1 = new BreadCrumbLink("", (String) null, true, "");
      breadCrumbLink0.setPrevious(breadCrumbLink1);
      assertTrue(breadCrumbLink1.isCurrentPage());
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("", "", true, "");
      boolean boolean0 = breadCrumbLink0.isCurrentPage();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("", "", true, "");
      breadCrumbLink0.setUrl("");
      breadCrumbLink0.getUrl();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("", "", true, "");
      breadCrumbLink0.setPrevious(breadCrumbLink0);
      BreadCrumbLink breadCrumbLink1 = breadCrumbLink0.getPrevious();
      assertTrue(breadCrumbLink1.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("dummiesmind.breadcrumb.springmvc.breadcrumb.BreadCrumbLink", ",@b,q.).KS", false, "");
      breadCrumbLink0.setPrevious(breadCrumbLink0);
      BreadCrumbLink breadCrumbLink1 = breadCrumbLink0.getPrevious();
      assertEquals("", breadCrumbLink1.getParentKey());
      assertFalse(breadCrumbLink1.isCurrentPage());
      assertEquals(",@b,q.).KS", breadCrumbLink1.getLabel());
      assertEquals("dummiesmind.breadcrumb.springmvc.breadcrumb.BreadCrumbLink", breadCrumbLink1.getFamily());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("", "", true, "");
      breadCrumbLink0.setParentKey((String) null);
      breadCrumbLink0.getParentKey();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("", "", true, "");
      breadCrumbLink0.getParentKey();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("Ai\"D8N:/F/", "Ai\"D8N:/F/", true, "Ai\"D8N:/F/");
      breadCrumbLink0.setParent(breadCrumbLink0);
      BreadCrumbLink breadCrumbLink1 = breadCrumbLink0.getParent();
      assertTrue(breadCrumbLink1.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("Ai\"D8N:/F/", "Ai\"D8N:/F/", true, "Ai\"D8N:/F/");
      breadCrumbLink0.addNext(breadCrumbLink0);
      breadCrumbLink0.getNext();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink((String) null, (String) null, false, "");
      String string0 = breadCrumbLink0.getLabel();
      assertNull(string0);
      assertFalse(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("", "", true, "");
      breadCrumbLink0.getLabel();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("", "", true, "");
      breadCrumbLink0.setFamily((String) null);
      breadCrumbLink0.getFamily();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("", "", true, "");
      breadCrumbLink0.getFamily();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("$", "$", true, "$");
      breadCrumbLink0.setUrl("$");
      breadCrumbLink0.getUrl();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("", "", false, "");
      boolean boolean0 = breadCrumbLink0.isCurrentPage();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("@", "@", false, "@");
      breadCrumbLink0.setLabel("@");
      assertFalse(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("$", "$", true, "$");
      breadCrumbLink0.getFamily();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("$", "$", true, "$");
      breadCrumbLink0.getNext();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("$", "$", true, "$");
      breadCrumbLink0.getPrevious();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("$", "$", true, "$");
      breadCrumbLink0.getLabel();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("@", "@", false, "@");
      breadCrumbLink0.setParent(breadCrumbLink0);
      BreadCrumbLink breadCrumbLink1 = breadCrumbLink0.getParent();
      assertFalse(breadCrumbLink1.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("$", "$", true, "$");
      breadCrumbLink0.getParentKey();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("$", "$", true, "$");
      breadCrumbLink0.getUrl();
      assertTrue(breadCrumbLink0.isCurrentPage());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      BreadCrumbLink breadCrumbLink0 = new BreadCrumbLink("@", "@", false, "@");
      breadCrumbLink0.getParent();
      assertFalse(breadCrumbLink0.isCurrentPage());
  }
}
