/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 12 15:09:07 GMT 2019
 */

package org.springframework.samples.petclinic.evo_ten_seconds;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.samples.petclinic.model.NamedEntity;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class NamedEntity_ESTest extends NamedEntity_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NamedEntity namedEntity0 = new NamedEntity();
      namedEntity0.setName("f?8&z_,bkE;bhG{>");
      String string0 = namedEntity0.toString();
      assertEquals("f?8&z_,bkE;bhG{>", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NamedEntity namedEntity0 = new NamedEntity();
      namedEntity0.setName("");
      String string0 = namedEntity0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NamedEntity namedEntity0 = new NamedEntity();
      namedEntity0.setName("vg)0qAL<1&pp.d67");
      String string0 = namedEntity0.getName();
      assertEquals("vg)0qAL<1&pp.d67", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NamedEntity namedEntity0 = new NamedEntity();
      namedEntity0.setName("");
      String string0 = namedEntity0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NamedEntity namedEntity0 = new NamedEntity();
      String string0 = namedEntity0.toString();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NamedEntity namedEntity0 = new NamedEntity();
      String string0 = namedEntity0.getName();
      assertNull(string0);
  }
}
