/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 12 15:10:56 GMT 2019
 */

package org.springframework.samples.petclinic.evo_ten_seconds;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.samples.petclinic.system.WelcomeController;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class WelcomeController_ESTest extends WelcomeController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WelcomeController welcomeController0 = new WelcomeController();
      String string0 = welcomeController0.welcome();
      assertEquals("welcome", string0);
  }
}
